name: GitHub Action Demo
on: push
jobs:
  baction-demo:    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code 
        uses: actions/checkout@v4
      - name: Print indec.html file
        run : cat index.html
