name: paraller_jobs
on: workflow_dispatch
jobs:
  build:   # this is my frist Job 
    runs-on: ubuntu-latest
    steps:
      - name: Build step
        run: echo "A demo build"
  test:  # this is my second Job 
    runs-on: ubuntu-latest
    needs: build 
    steps:
      - name: Test phase
        run: echo "running test cases"
  deploy:  # this is my third Job 
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: deploy the app
        run: echo "deploying the app" 
