name: Deploy HTML to S3
on: puch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code form repo
        user: action/checkout@/v4
      - name: configure aws
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          aws-region: us-east-1
